public enum RatingDebugOption
{
	INVALID = 0,
	RANKED_STANDARD = 1,
	CASUAL_STANDARD = 2,
	ARENA = 3,
	TAVERN_BRAWL = 4,
	RANKED_WILD = 5,
	CASUAL_WILD = 6,
	BATTLEGROUNDS = 8,
	PVP_DUNGEON_RUN = 9,
	PVP_DUNGEON_RUN_PAID = 10,
	RANKED_CLASSIC = 12,
	CASUAL_CLASSIC = 13,
	MERCENARIES = 14
}
