public enum ShopType
{
	GENERAL_STORE = 0,
	ARENA_STORE = 1,
	ADVENTURE_STORE = 2,
	TAVERN_BRAWL_STORE = 3,
	ADVENTURE_STORE_WING_PURCHASE_WIDGET = 4,
	ADVENTURE_STORE_FULL_PURCHASE_WIDGET = 5,
	DEPRECATED_DUELS_STORE = 6,
	CARD_BACK_STORE = 7,
	HERO_SKIN_STORE = 8,
	MERCENARIES_WORKSHOP = 11,
	LUCKY_DRAW_STORE = 12
}
