namespace Blizzard.Telemetry.WTCG.Client;

public enum GameType
{
	GT_UNKNOWN = 0,
	GT_VS_AI = 1,
	GT_VS_FRIEND = 2,
	GT_TUTORIAL = 4,
	GT_ARENA = 5,
	GT_TEST_AI_VS_AI = 6,
	GT_RANKED = 7,
	GT_CASUAL = 8,
	GT_TAVERNBRAWL = 16,
	GT_FSG_BRAWL_VS_FRIEND = 19,
	GT_FSG_BRAWL = 20,
	GT_BATTLEGROUNDS = 23,
	GT_BATTLEGROUNDS_FRIENDLY = 24,
	GT_PVPDR_PAID = 28,
	GT_PVPDR_CASUAL = 29,
	GT_LETTUCE = 30,
	GT_LETTUCE_VS_AI = 31,
	GT_MERCENARIES_PVE_COOP = 32,
	GT_MERCENARIES_AI_VS_AI = 33,
	GT_MERCENARIES_FRIENDLY = 34,
	GT_BATTLEGROUNDS_AI_VS_AI = 35,
	GT_BATTLEGROUNDS_PLAYER_VS_AI = 36,
	GT_BATTLEGROUNDS_DUO = 37,
	GT_BATTLEGROUNDS_DUO_VS_AI = 38,
	GT_BATTLEGROUNDS_DUO_FRIENDLY = 39,
	GT_BATTLEGROUNDS_DUO_AI_VS_AI = 40,
	GT_BATTLEGROUNDS_DUO_1_PLAYER_VS_AI = 41
}
